language: c

install:
  - sudo apt-get install libmpc-dev
  - sudo apt-get install nasm
  - sudo apt-get install xorriso
  - make toolchain

script: make

cache:
  directories:
    - $HOME/bauen1/brainOS/toolchain/opt
