language: c

install:
  - sudo apt-get install libmpc-dev
  - sudo apt-get install nasm
  - sudo apt-get install xorriso
  - ./toolchain/build-travis.sh

script: make all PREFIX="$HOME/toolchain/opt/cross"

cache:
  directories:
    - $HOME/toolchain/opt
