language: c

install:
  - sudo apt-get install libmpc-dev
  - sudo apt-get install nasm
  - sudo apt-get install xorriso
  - ./toolchain/build-travis.sh

script: make all prefix="$HOME/opt/cross"

tests: make tests prefix="$HOME/opt/cross"

cache:
  directories:
    - $HOME/opt/cross/
