#ifndef VMM_H
#define VMM_H

#include <stdint.h>

#define VMM_PAGE_TABLE_ENTRY_PRESENT          0x01
#define VMM_PAGE_TABLE_ENTRY_READWRITE        0x02
#define VMM_PAGE_TABLE_ENTRY_USER             0x04
#define VMM_PAGE_TABLE_ENTRY_WRITE_THROUGH    0x08
#define VMM_PAGE_TABLE_ENTRY_CACHE_DISABLE    0x10
#define VMM_PAGE_TABLE_ENTRY_ACCESSED         0x20
#define VMM_PAGE_TABLE_ENTRY_PAGE_SIZE        0x40

#define VMM_PAGE_DIRECTORY_ENTRY_PRESENT          0x01
#define VMM_PAGE_DIRECTORY_ENTRY_READWRITE        0x02
#define VMM_PAGE_DIRECTORY_ENTRY_USER             0x04
#define VMM_PAGE_DIRECTORY_ENTRY_WRITE_THROUGH    0x08
#define VMM_PAGE_DIRECTORY_ENTRY_CACHE_DISABLE    0x10
#define VMM_PAGE_DIRECTORY_ENTRY_ACCESSED         0x20
#define VMM_PAGE_DIRECTORY_ENTRY_PAGE_SIZE        0x80


void vmm_init();

#endif
